# Generated by Django 5.1.2 on 2024-10-31 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(blank=True, max_length=1000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('quantidade_estoque', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('imagem', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteora.categoria')),
            ],
        ),
    ]
