# Generated by Django 5.1.2 on 2024-11-01 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meteora', '0003_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_fotografia',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='produto',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
